### ISSUE TITLE
俄罗斯L20升级

### ISSUE THREAD

**Issue by liuruisky** [tigerzhang/3rd-support#2]
升级流程
1. 修改L20地址到jt.yunba.io  5015  ----俄罗斯操作

2.升级GSM程序
升级文本指令数据为
*269#W,121.199.26.185,8955,GSM-2.01.03,GSM,1;
对应的协议数据
7e8300002e017030800060000a002a32363923572c3132312e3139392e32362e3138352c383935352c47534d2d322e30312e30332c47534d2c313b4a7e
格式组包参照协议 8300

建议平台做属性查询,查询终端版本信息，这样判断是否升级成功
7e810700000170308000600003247e
查询终端版本号

3. 升级成功后，如果版本正确，下发参数修改为蓝牙低功耗模式，修改密钥，重启车锁

**Comment by tigerzhang** [comment]
@liuruisky 两个问题：

1. "升级文本指令数据为.. 格式组包参照协议 8300。"<---  这个是用 8300 包一个文本指令下发吗？
2. "建议平台做属性查询,查询终端版本信息" <--- 现在应该是从哪个版本升级到哪个版本？

**Comment by tigerzhang** [comment]
@johnzeng @yezhenbang-yunba
